### ISSUE TITLE
Bug in Response model method

### ISSUE THREAD

**Issue by mckaz** [nbudin/journey#167]
The issue is on this line: https://github.com/nbudin/journey/blob/master/app/models/response.rb#L20

The problem is there is no constant `Field` (in this environment) so this will raise a runtime error. Maybe this is supposed to be `Questions::Field`?

**Comment by nbudin** [comment]
Yup, you're absolutely right.

I'm actually a little curious about how on earth this isn't causing a RuntimeError for me.  Could you tell me a little about the environment you're running it in so I can compare?  (Ruby version, web server, etc.)

**Comment by nbudin** [comment]
Ah, I think I see what's going on.  `verify_answers_for_page` and `verify_answers` are some old methods that used to be called from a controller, but are never actually called anymore.  (I think the time when these used to be called was before I created the `Questions::` namespace.)

To fix this, what I should really do is delete this dead code.

**Comment by nbudin** [comment]
Dead code gone.  Thanks again for the heads up!
