### ISSUE TITLE
Welcome page has out of date donation link

### ISSUE THREAD

**Issue by danielhjames** [nbudin/journey#185]
http://welcome.journeysurveys.com/ features an out of date donation link:

`Journey is user-supported; click <a href="http://www.pledgie.com/campaigns/19233">here</a> to make a donation.</p>`

I would send a pull request, but this page does not appear to be part of the project source.

**Comment by nbudin** [comment]
Thanks!  Fixing.

**Comment by nbudin** [comment]
I actually can't even find where I put the code for the marketing site, facepalm.  But I did fix it manually via S3. 😬

**Comment by danielhjames** [comment]
Thanks Nat, you might like to add the link to http://welcome.journeysurveys.com/pricing/ also, which mentions donations.

**Comment by nbudin** [comment]
Good looking out, thanks!  That's also fixed now.  (It used to have a Pledgie link, but that wasn't even loading at all so it didn't appear on the page.)
