### ISSUE TITLE
Link to Sugar Pond website is timing out

### ISSUE THREAD

**Issue by danielhjames** [nbudin/journey#198]
Hi Nat,

On http://welcome.journeysurveys.com/about-us/ the link to https://www.sugarpond.net/ is timing out with error 522 on a Cloudflare error page. Not a complaint, just thought you'd like to know if you don't already.

Thanks for making the new Journey releases :-)

**Comment by nbudin** [comment]
Hi Daniel, thanks for letting me know!  I had misconfigured a setting in Cloudflare, but I've fixed it and it should be working again now.

**Comment by danielhjames** [comment]
Works for me now :-)
